
# Navsat (convert GPS coordinates to Cartesian)
navsat:
  frequency: 50
  wait_for_datum: true
  delay: 0.0
  magnetic_declination_radians: 0
  yaw_offset: 0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: false
  ## DOMOKOS DATUM
  datum:
  - 39.083527376
  - 22.3332770044
  - 0.0186451
  - map
  - aristos_base_footprint

# EKF for Navsat
ekf_gps:
  publish_tf: true
  odom_frame: aristos_odom
  base_link_frame: aristos_base_footprint
  world_frame: map

  frequency: 50
  two_d_mode: $(arg two_d_mode)
  sensor_timeout: 0.01
  # -------------------------------------
  # External IMU:
  # -------------------------------------
  imu0: imu/data/modified_covariances
  # make sure the input is aligned with ROS REP105. "imu_correct" is manually transformed by myself. EKF can also transform the data using tf between your imu and base_link
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                false, false, true,
                false, false, false,]
  imu0_differential: false
  imu0_queue_size: 50 
  imu0_remove_gravitational_acceleration: true

  # odom3: gnss_heading/odom
  # odom3_config: [false,  false,  false,
  #                true, true, true,
  #                false, false,  false,
  #                false, false, false,
  #                false, false, false]
  # odom3_differential: false
  # odom3_queue_size: 50

  # -------------------------------------
  # Odometry (From Navsat):
  # -------------------------------------
  odom0: odometry/gps/onlyRTK$(arg rtk_relay_extension)
  # odom0: odometry/gps #use with navsat node
  odom0_config: [true,  true,  false,
                 false, false, false,
                 false, false, false,
                 false, false, false,
                 false, false, false]
  odom0_differential: false
  odom0_queue_size: 10

  # -------------------------------------
  # Odometry (From FAST-LIO):
  # -------------------------------------
  odom1: Odometry
  odom1_config: [true,  true,  true,
                 true,  true,  true,
                 false, false, false,
                 false, false, false,
                 false, false, false]
  odom1_differential: true
  odom1_queue_size: 10

  # odom3: Odometry
  # odom3_config: [false, false, false,
  #                true,  true,  true,
  #                false, false, false,
  #                false, false, false,
  #                false, false, false]
  # odom3_differential: false
  # odom3_queue_size: 10

  # -------------------------------------
  # Wheel Odometry 
  # -------------------------------------
  odom2: wheel/odom_relay
  odom2_config: [false,  false,  false,
                 false, false,  false,
                 true, true, true,
                 false, false, false,
                 false, false, false]
  odom2_differential: false
  odom2_queue_size: 10

  #                            x     y     z     r     p     y   x_dot  y_dot  z_dot  r_dot p_dot y_dot x_ddot y_ddot z_ddot
  process_noise_covariance: [  1.0,  0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    1.0,  0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    10.0, 0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0.03, 0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0.03, 0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0.1,  0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0.25,  0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0.25,  0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0.04,  0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0.01, 0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0.01, 0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0.5,  0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0.01, 0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0.01,   0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0.015]
