common:
    # lid_topic:  "/livox/points"
    # imu_topic:  "/livox/imu"
    lid_topic:  "/aristos/livox/lidar" 
    imu_topic:  "/aristos/imu/data" 
    init_frame: "aristos_odom"
    body_frame: "aristos_base_footprint"
    # It seems that FAST-LIO returns the IMU frame, thus setting the body_frame as the imu_link is the correct.
    # This requires that FAST-LIO does not publish to /tf and a local ekf creates the transform odom->base_link, i.e.,  fast_lio_publish_tf: false
    # However, for practical reasons of aristos application base_link and imu_link does not make difference, 
    # hence body_frame: "aristos/base_link" && fast_lio_publish_tf: true remain the default
    # body_frame: "aristos/imu_link" # if fast_lio_publish_tf == false
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 4
    blind: 0.5

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    360
    det_range:     100.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic

    #DOMOKOS extrinsics
    # extrinsic_T: [0.209, 0.008, 0.420]
    # # extrinsic_R: [-1, 0, 0,
    # #                 0, -1, 0,
    # #                 0, 0, 1]     
    # # -0.02563 rad pitch
    # extrinsic_R: [  -1.000000,  0.0000000, -0.0256272,
    #                 0.0000000, -1.0000000,  0.0000000,
    #                 -0.0256272, 0.0000000,  1.000000 ]

    #FERRARA
    # extrinsic_T: [0.387, 0.008, 0.411]
    # # 0.008 rad pitch teleop
    # # -0.0380 rad pitch autonomous
    # extrinsic_R: [  0.0000000,  1.0000000,  -0.008,
    #                 -1.000000,  0.0000000,  0.0000000,
    #                 0.0000000,  0.008,  1.0000000 ]

    #DOMOKOS 2
    extrinsic_T: [0.387, 0.008, 0.411]
    # 0.008 rad pitch teleop
    # -0.0380 rad pitch autonomous
    extrinsic_R: [  0.0000000,  1.0000000,  0.077,
                    -1.000000,  0.0000000,  0.0000000,
                    0.0000000,  -0.077,  1.0000000 ]



publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
    tf: $(arg fast_lio_publish_tf)

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
